bux API Reference: bux::C_AutoNode< T > Class Template Reference
bux::C_AutoNode< T > Class Template Reference
#include <XAutoPtr.h>
Public Member Functions
constexpr C_AutoNode () noexcept
constexpr C_AutoNode (T *p, bool owned) noexcept
C_AutoNode (C_AutoNode &another) noexcept
template<class T2>
C_AutoNode (C_AutoNode< T2 > &another) noexcept
~C_AutoNode ()
void operator= (C_AutoNode &another)
template<class T2>
void operator= (C_AutoNode< T2 > &another)
operator bool () const noexcept
template<class T2>
operator T2 * () const noexcept
T * operator-> () const noexcept
T ** operator& () noexcept
T & operator* () const noexcept
void assign (T *ptr, bool owned)
void reset (T *ptr) noexcept
void clear () noexcept
T * disown () noexcept
T * get () const noexcept
bool owned () const noexcept
void swap (C_AutoNode &another) noexcept
template<class T2>
bool takeOver (C_AutoNode< T2 > &another)
Friends
template<class T2>
class C_AutoNode
Detailed Description
template<class T>
class bux::C_AutoNode< T >
Definition at line 12 of file XAutoPtr.h.
Constructor & Destructor Documentation
C_AutoNode() [1/4]
template<class T> bux::C_AutoNode< T >::C_AutoNode () inline constexpr noexcept
Definition at line 17 of file XAutoPtr.h.
C_AutoNode() [2/4]
template<class T> bux::C_AutoNode< T >::C_AutoNode (T * p, bool owned) inline constexpr noexcept
Definition at line 18 of file XAutoPtr.h.
C_AutoNode() [3/4]
template<class T> bux::C_AutoNode< T >::C_AutoNode (C_AutoNode< T > & another) inline explicit noexcept
Definition at line 19 of file XAutoPtr.h.
C_AutoNode() [4/4]
template<class T> template<class T2> bux::C_AutoNode< T >::C_AutoNode (C_AutoNode< T2 > & another) inline explicit noexcept
Definition at line 22 of file XAutoPtr.h.
~C_AutoNode()
template<class T> bux::C_AutoNode< T >::~C_AutoNode ()
Definition at line 72 of file XAutoPtr.h.
Member Function Documentation
assign()
template<class T> void bux::C_AutoNode< T >::assign (T * ptr, bool owned)
Definition at line 94 of file XAutoPtr.h.
References C_AutoNode, and owned().
Referenced by bux::LR1::C_Parser::add(), bux::C_AutoNode< I_LexAttr >::clear(), bux::C_AutoNode< I_LexAttr >::operator&(), bux::C_AutoNode< I_LexAttr >::reset(), and takeOver().
clear()
template<class T> void bux::C_AutoNode< T >::clear () inline noexcept
Definition at line 36 of file XAutoPtr.h.
disown()
template<class T> T * bux::C_AutoNode< T >::disown () noexcept
Definition at line 101 of file XAutoPtr.h.
get()
template<class T> T * bux::C_AutoNode< T >::get () const inline noexcept
Definition at line 38 of file XAutoPtr.h.
Referenced by takeOver().
operator bool()
template<class T> bux::C_AutoNode< T >::operator bool () const inline noexcept
Definition at line 28 of file XAutoPtr.h.
operator T2 *()
template<class T> template<class T2> bux::C_AutoNode< T >::operator T2 * () const inline noexcept
Definition at line 30 of file XAutoPtr.h.
operator&()
template<class T> T ** bux::C_AutoNode< T >::operator& () inline noexcept
Definition at line 32 of file XAutoPtr.h.
operator*()
template<class T> T & bux::C_AutoNode< T >::operator* () const inline noexcept
Definition at line 33 of file XAutoPtr.h.
operator->()
template<class T> T * bux::C_AutoNode< T >::operator-> () const inline noexcept
Definition at line 31 of file XAutoPtr.h.
operator=() [1/2]
template<class T> void bux::C_AutoNode< T >::operator= (C_AutoNode< T > & another)
Definition at line 79 of file XAutoPtr.h.
References C_AutoNode.
operator=() [2/2]
template<class T> template<class T2> void bux::C_AutoNode< T >::operator= (C_AutoNode< T2 > & another)
Definition at line 87 of file XAutoPtr.h.
References C_AutoNode.
owned()
template<class T> bool bux::C_AutoNode< T >::owned () const inline noexcept
Definition at line 39 of file XAutoPtr.h.
Referenced by assign().
reset()
template<class T> void bux::C_AutoNode< T >::reset (T * ptr) inline noexcept
Definition at line 35 of file XAutoPtr.h.
swap()
template<class T> void bux::C_AutoNode< T >::swap (C_AutoNode< T > & another) noexcept
Definition at line 112 of file XAutoPtr.h.
References C_AutoNode.
takeOver()
template<class T> template<class T2> bool bux::C_AutoNode< T >::takeOver (C_AutoNode< T2 > & another)
Definition at line 125 of file XAutoPtr.h.
References assign(), C_AutoNode, and get().
Friends And Related Symbol Documentation
C_AutoNode
template<class T> template<class T2> friend class C_AutoNode friend
Definition at line 51 of file XAutoPtr.h.
Referenced by assign(), bux::C_NewNode< T >::C_NewNode(), bux::C_NewNode< T >::C_NewNode(), operator=(), operator=(), swap(), and takeOver().
The documentation for this class was generated from the following file:
XAutoPtr.h