bux API Reference: bux::C_UseLog Class Reference
bux::C_UseLog Class Reference
#include <SyncLog.h>
Public Member Functions
C_UseLog (I_SyncLog &obj)
C_UseLog (I_SyncLog &obj, E_LogLevel level)
~C_UseLog ()
operator bool () const
auto & operator* () const
auto stream () const
Detailed Description
Helper class to use logger in the current thread while blocking any other thread from using it.
Definition at line 195 of file SyncLog.h.
Constructor & Destructor Documentation
C_UseLog() [1/2]
bux::C_UseLog::C_UseLog (I_SyncLog & obj) inline
Definition at line 202 of file SyncLog.h.
C_UseLog() [2/2]
bux::C_UseLog::C_UseLog (I_SyncLog & obj, E_LogLevel level) inline
Definition at line 203 of file SyncLog.h.
~C_UseLog()
bux::C_UseLog::~C_UseLog () inline
Definition at line 204 of file SyncLog.h.
References bux::I_SyncLog::unlockLog().
Member Function Documentation
operator bool()
bux::C_UseLog::operator bool () const inline
Definition at line 209 of file SyncLog.h.
operator*()
auto & bux::C_UseLog::operator* () const inline
Definition at line 210 of file SyncLog.h.
stream()
auto bux::C_UseLog::stream () const inline
Definition at line 211 of file SyncLog.h.
Referenced by bux::C_UseLogger::C_UseLogger(), and bux::C_UseTraceLog::C_UseTraceLog().
The documentation for this class was generated from the following file:
SyncLog.h