bux API Reference: bux::C_NFA< T_Inputs, T_Action, C_Traits > Class Template Reference
bux::C_NFA< T_Inputs, T_Action, C_Traits > Class Template Reference
#include <FA.h>
Public Member Functions
C_NFA ()=default
C_NFA (const C_NFA &a)
C_NFA (C_NFA &&a)
C_NFA (const T_Inputs &inputs)
void operator= (const C_NFA &a)
void operator= (C_NFA &&a)
void operator|= (const C_NFA &a)
void operator+= (const C_NFA &a)
void operator+= (const T_Inputs &inputs)
C_NFA & append (const C_NFA &a)
C_NFA & append (const T_Inputs &inputs)
C_NFA & changeTo (int options)
template<class T>
void setAction (T &&action)
size_t totalFinalStates () const
Friends
class C_DFA< T_Inputs, T_Action, C_Traits >
Detailed Description
template<class T_Inputs, class T_Action, class C_Traits = C_FA_Traits<T_Inputs>>
class bux::C_NFA< T_Inputs, T_Action, C_Traits >
Parameters
T_Inputs Set of inputs
T_Action Type of action on final state.
C_Traits Collection of compile-time decisions
NFA stands for Nondeterministic Finite Automoton
Definition at line 59 of file FA.h.
Constructor & Destructor Documentation
C_NFA() [1/4]
template<class T_Inputs, class T_Action, class C_Traits = C_FA_Traits<T_Inputs>> bux::C_NFA< T_Inputs, T_Action, C_Traits >::C_NFA () default
Referenced by append(), append(), C_NFA(), C_NFA(), changeTo(), operator=(), operator=(), and operator|=().
C_NFA() [2/4]
template<class T_Inputs, class T_Action, class C_Traits> bux::C_NFA< T_Inputs, T_Action, C_Traits >::C_NFA (const C_NFA< T_Inputs, T_Action, C_Traits > & a)
Definition at line 222 of file FA.h.
References C_NFA().
C_NFA() [3/4]
template<class T_Inputs, class T_Action, class C_Traits> bux::C_NFA< T_Inputs, T_Action, C_Traits >::C_NFA (C_NFA< T_Inputs, T_Action, C_Traits > && a)
Definition at line 228 of file FA.h.
References C_NFA().
C_NFA() [4/4]
template<class T_Inputs, class T_Action, class C_Traits> bux::C_NFA< T_Inputs, T_Action, C_Traits >::C_NFA (const T_Inputs & inputs)
Definition at line 235 of file FA.h.
Member Function Documentation
append() [1/2]
template<class T_Inputs, class T_Action, class C_Traits> C_NFA< T_Inputs, T_Action, C_Traits > & bux::C_NFA< T_Inputs, T_Action, C_Traits >::append (const C_NFA< T_Inputs, T_Action, C_Traits > & a)
Definition at line 276 of file FA.h.
References C_NFA().
Referenced by bux::C_TransitionMap< T_Inputs, T_Action, C_Traits >::operator+=(), and bux::C_TransitionMap< T_Inputs, T_Action, C_Traits >::operator+=().
append() [2/2]
template<class T_Inputs, class T_Action, class C_Traits> C_NFA< T_Inputs, T_Action, C_Traits > & bux::C_NFA< T_Inputs, T_Action, C_Traits >::append (const T_Inputs & inputs)
Definition at line 295 of file FA.h.
References C_NFA().
changeTo()
template<class T_Inputs, class T_Action, class C_Traits> C_NFA< T_Inputs, T_Action, C_Traits > & bux::C_NFA< T_Inputs, T_Action, C_Traits >::changeTo (int options)
Definition at line 312 of file FA.h.
References C_NFA(), bux::FA_OPTIONAL, and bux::FA_REPEATABLE.
operator+=() [1/2]
template<class T_Inputs, class T_Action, class C_Traits = C_FA_Traits<T_Inputs>> void bux::C_NFA< T_Inputs, T_Action, C_Traits >::operator+= (const C_NFA< T_Inputs, T_Action, C_Traits > & a) inline
Definition at line 77 of file FA.h.
operator+=() [2/2]
template<class T_Inputs, class T_Action, class C_Traits = C_FA_Traits<T_Inputs>> void bux::C_NFA< T_Inputs, T_Action, C_Traits >::operator+= (const T_Inputs & inputs) inline
Definition at line 78 of file FA.h.
operator=() [1/2]
template<class T_Inputs, class T_Action, class C_Traits> void bux::C_NFA< T_Inputs, T_Action, C_Traits >::operator= (C_NFA< T_Inputs, T_Action, C_Traits > && a)
Definition at line 251 of file FA.h.
References C_NFA().
operator=() [2/2]
template<class T_Inputs, class T_Action, class C_Traits> void bux::C_NFA< T_Inputs, T_Action, C_Traits >::operator= (const C_NFA< T_Inputs, T_Action, C_Traits > & a)
Definition at line 243 of file FA.h.
References C_NFA().
operator|=()
template<class T_Inputs, class T_Action, class C_Traits> void bux::C_NFA< T_Inputs, T_Action, C_Traits >::operator|= (const C_NFA< T_Inputs, T_Action, C_Traits > & a)
Definition at line 259 of file FA.h.
References C_NFA().
setAction()
template<class T_Inputs, class T_Action, class C_Traits> template<class T> void bux::C_NFA< T_Inputs, T_Action, C_Traits >::setAction (T && action)
Definition at line 379 of file FA.h.
totalFinalStates()
template<class T_Inputs, class T_Action, class C_Traits = C_FA_Traits<T_Inputs>> size_t bux::C_NFA< T_Inputs, T_Action, C_Traits >::totalFinalStates () const inline
Definition at line 83 of file FA.h.
Friends And Related Symbol Documentation
C_DFA< T_Inputs, T_Action, C_Traits >
template<class T_Inputs, class T_Action, class C_Traits = C_FA_Traits<T_Inputs>> friend class C_DFA< T_Inputs, T_Action, C_Traits > friend
Definition at line 118 of file FA.h.
The documentation for this class was generated from the following file:
FA.h