bux API Reference: bux::C_FileLog Class Reference
bux::C_FileLog Class Reference
#include <FileLog.h>
Public Member Functions
C_FileLog (const std::string &pathFmt="%Y%m%d.log")
void configPath (const std::string &pathFmt)
void enableAutoMkDir (bool yes=true)
void setBinaryMode (bool enabled)
Public Member Functions inherited from bux::I_SyncResource< T >
virtual ~I_SyncResource ()=default
virtual void releaseResource (T res)=0
Protected Member Functions
std::ostream & getResource () override
void releaseResource (std::ostream &out) override
Detailed Description
Thread-safe file log which can be configured to automatically change the output path according to the current timestamp. Apply bux::C_UseOstream to block any other thread WITHIN process from using it.
Definition at line 14 of file FileLog.h.
Constructor & Destructor Documentation
C_FileLog()
bux::C_FileLog::C_FileLog (const std::string & _pathFmt = "%Y%m%d.log") explicit
Parameters
[in] _pathFmt Path formatting string. The default string "\%Y\%m\%d.log" is for daily report.
What this constructor does is simply call configPath(_pathFmt) and enableAutoMkDir(true).
Example:
//
// Programming IVR global log files
//
C_FileLog   BillingLog(".\\billinglog\\%Y%m%d.bil");            // daily
C_FileLog   RatingLog(".\\billinglog\\%Y%m\\%d_outbound.log");  // daily
C_FileLog   ErrorLog(".\\log\\%Y%m%p_err.log");     // half-daily
C_FileLog   DbLog(".\\log\\%Y%m%d%H_db.log");       // hourly
C_FileLog   ActivityLog(".\\log\\%Y%mcall.log");    // monthly
Definition at line 12 of file FileLog.cpp.
References configPath().
Member Function Documentation
configPath()
void bux::C_FileLog::configPath (const std::string & _pathFmt)
Parameters
[in] _pathFmt The third argument of ANSI C time function strftime(), see MSDN Library for help. Everytime when virtual method getResource() gets called, the current log path is regenerated according to this format string and the current timestamp to compare with the previous one. Were they different, the internal file stream is reopenned on the new path. Here is the format spec for your convience:
The format argument consists of one or more codes; as in printf(), the formatting codes are preceded by a percent sign (%). Characters that do not begin with % are copied unchangedly. The LC_TIME category of the current locale affects the output formatting of strftime. (For more information on LC_TIME, see setlocale().) The formatting codes for strftime() are listed below:
%a
Abbreviated weekday name
%A
Full weekday name
%b
Abbreviated month name
%B
Full month name
%c
Date and time representation appropriate for locale
%d
Day of month as decimal number (01 - 31)
%H
Hour in 24-hour format (00 - 23)
%I
Hour in 12-hour format (01 - 12)
%j
Day of year as decimal number (001 - 366)
%m
Month as decimal number (01 - 12)
%M
Minute as decimal number (00 - 59)
%p
Current locale's A.M./P.M. indicator for 12-hour clock
%S
Second as decimal number (00 - 59)
%U
Week of year as decimal number, with Sunday as first day of week (00 - 53)
%w
Weekday as decimal number (0 - 6; Sunday is 0)
%W
Week of year as decimal number, with Monday as first day of week (00 - 53)
%x
Date representation for current locale
%X
Time representation for current locale
%y
Year without century, as decimal number (00 - 99)
%Y
Year with century, as decimal number
%z, %Z
Time-zone name or abbreviation; no characters if time zone is unknown
%%
Percent sign
As in the printf function, the # flag may prefix any formatting code. In that case, the meaning of the format code is changed as follows.
Format Code Meaning
%#a, %#A, %#b, %#B, %#p, %#X, %#z, %#Z, %#% # flag is ignored.
%#c Long date and time representation, appropriate for current locale. For example: "Tuesday, March 14, 1995, 12:41:29".
%#x Long date representation, appropriate to current locale. For example: "Tuesday, March 14, 1995".
%#d, %#H, %#I, %#j, %#m, %#M, %#S, %#U, %#w, %#W, %#y, %#Y Remove leading zeros (if any).
Example: see construct.
Precondition
_pathFmt is not empty.
Definition at line 36 of file FileLog.cpp.
References RUNTIME_ERROR.
Referenced by C_FileLog().
enableAutoMkDir()
void bux::C_FileLog::enableAutoMkDir (bool yes = true)
Parameters
[in] yes Whether or not to create subdirectory for the openning log path. The default is true.
If enabled, getResource() always creates the subdir before openning the log path no matter how deep the subdir is.
Since constructor always enables it, you hradly need to call this method explicitly.
Definition at line 165 of file FileLog.cpp.
getResource()
std::ostream & bux::C_FileLog::getResource () override protected virtual
Implements bux::I_SyncResource< T >.
Definition at line 179 of file FileLog.cpp.
References bux::C_SyncOstream::getResource(), and RUNTIME_ERROR.
releaseResource()
void bux::C_FileLog::releaseResource (std::ostream & out) override protected
Definition at line 224 of file FileLog.cpp.
References bux::C_SyncOstream::releaseResource().
setBinaryMode()
void bux::C_FileLog::setBinaryMode (bool enabled)
Definition at line 229 of file FileLog.cpp.
The documentation for this class was generated from the following files:
FileLog.h
FileLog.cpp