bux API Reference: bux::C_ParaLog::C_NodeProxy Class Reference
bux::C_ParaLog::C_NodeProxy Class Reference
#include <ParaLog.h>
Public Member Functions
C_NodeProxy (std::recursive_mutex &lock, C_Node &node)
template<std::derived_from< I_ReenterableLog > T>
bool addChild (std::unique_ptr< T > &&snap) const
bool addChild (std::ostream &out, E_LogLevel ll=LL_VERBOSE) const
bool addChild (I_SnapT< std::ostream * > &snap, E_LogLevel ll=LL_VERBOSE) const
template<class C_LogImpl , class C_Holder = typename C_AutoSinkHolderT<C_LogImpl>::type, E_LogLevel LL = LL_VERBOSE, class... T_Args>
bool addChildT (T_Args &&...args) const
C_NodeArrayProxy partitionBy (std::convertible_to< FC_Accept > auto f) const
template<typename Filters >
requires requires
C_NodeArrayProxy partitionBy (Filters fs) const
dst m_filteredNodes reserve (std::size(fs))
Public Attributes
auto & dst = m_node->m_partitions.emplace_back()
for(auto &&i:fs) dst.m_filteredNodes.emplace_back(std return {*m_lock, dst}
Detailed Description
Definition at line 112 of file ParaLog.h.
Constructor & Destructor Documentation
C_NodeProxy()
bux::C_ParaLog::C_NodeProxy::C_NodeProxy (std::recursive_mutex & lock, C_Node & node) inline
Definition at line 117 of file ParaLog.h.
Member Function Documentation
addChild() [1/3]
bool bux::C_ParaLog::C_NodeProxy::addChild (I_SnapT< std::ostream * > & snap, E_LogLevel ll = LL_VERBOSE) const inline
Definition at line 133 of file ParaLog.h.
References addChild().
addChild() [2/3]
bool bux::C_ParaLog::C_NodeProxy::addChild (std::ostream & out, E_LogLevel ll = LL_VERBOSE) const inline
Definition at line 129 of file ParaLog.h.
References addChild().
addChild() [3/3]
template<std::derived_from< I_ReenterableLog > T> bool bux::C_ParaLog::C_NodeProxy::addChild (std::unique_ptr< T > && snap) const inline
Definition at line 119 of file ParaLog.h.
Referenced by addChild(), bux::C_ParaLog::addChild(), and addChildT().
addChildT()
template<class C_LogImpl , class C_Holder = typename C_AutoSinkHolderT<C_LogImpl>::type, E_LogLevel LL = LL_VERBOSE, class... T_Args> bool bux::C_ParaLog::C_NodeProxy::addChildT (T_Args &&... args) const inline
Definition at line 138 of file ParaLog.h.
References addChild().
Referenced by bux::C_ParaLog::addChildT().
partitionBy() [1/2]
template<typename Filters > requires requires C_NodeArrayProxy bux::C_ParaLog::C_NodeProxy::partitionBy (Filters fs) const inline
Definition at line 150 of file ParaLog.h.
partitionBy() [2/2]
C_NodeArrayProxy bux::C_ParaLog::C_NodeProxy::partitionBy (std::convertible_to< FC_Accept > auto f) const inline
Definition at line 142 of file ParaLog.h.
References dst.
Referenced by bux::C_ParaLog::partitionBy().
reserve()
dst m_filteredNodes bux::C_ParaLog::C_NodeProxy::reserve (std::size(fs))
Member Data Documentation
dst
auto& bux::C_ParaLog::C_NodeProxy::dst = m_node->m_partitions.emplace_back()
Definition at line 157 of file ParaLog.h.
Referenced by partitionBy().
return
for (auto &&i: fs) dst.m_filteredNodes.emplace_back(std bux::C_ParaLog::C_NodeProxy::return {*m_lock, dst}
Definition at line 162 of file ParaLog.h.
The documentation for this class was generated from the following file:
ParaLog.h