bux API Reference: bux::GLR::C_Parser Class Reference
bux::GLR::C_Parser Class Reference
#include <GLR.h>
Public Member Functions
C_Parser (const I_ParserPolicy &policy)
void eachAccepted (std::function< void(C_LexPtr &)> apply)
void onError (const C_SourcePos &pos, std::string_view message)
void userData (void *p)
void * userData () const
void add (T_LexID token, unsigned line, unsigned col, I_LexAttr *unownedAttr) override
std::string_view setSource (std::string_view src) override
Public Member Functions inherited from bux::I_Parser
virtual ~I_Parser ()=default
Public Attributes
const I_ParserPolicy & m_policy
Detailed Description
Definition at line 58 of file GLR.h.
Constructor & Destructor Documentation
C_Parser()
bux::GLR::C_Parser::C_Parser (const I_ParserPolicy & policy)
Definition at line 45 of file GLR.cpp.
Member Function Documentation
add()
void bux::GLR::C_Parser::add (T_LexID token, unsigned line, unsigned col, I_LexAttr * unownedAttr) override virtual
Implements bux::I_Parser.
Definition at line 56 of file GLR.cpp.
References bux::GLR::I_ParserPolicy::action(), bux::GLR::ACTION_ACCEPT, bux::GLR::ACTION_REDUCE_MIN, bux::GLR::ACTION_SHIFT, bux::GLR::I_ParserPolicy::changeToken(), bux::GLR::I_ParserPolicy::getAcceptId(), HRTN, bux::C_LexInfoT< T, C_Ptr >::m_attr, bux::C_SourcePos::m_Col, bux::C_SourcePos::m_Line, m_policy, bux::C_LexInfoT< T, C_Ptr >::m_pos, bux::C_SourcePos::m_Source, bux::GLR::I_ParserPolicy::nextState(), onError(), and bux::GLR::I_ParserPolicy::printToken().
eachAccepted()
void bux::GLR::C_Parser::eachAccepted (std::function< void(C_LexPtr &)> apply)
Definition at line 185 of file GLR.cpp.
onError()
void bux::GLR::C_Parser::onError (const C_SourcePos & pos, std::string_view message)
Definition at line 191 of file GLR.cpp.
References m_policy, and bux::GLR::I_ParserPolicy::onError().
Referenced by add().
setSource()
std::string_view bux::GLR::C_Parser::setSource (std::string_view src) override virtual
Implements bux::I_Parser.
Definition at line 229 of file GLR.cpp.
userData() [1/2]
void * bux::GLR::C_Parser::userData () const inline
Definition at line 70 of file GLR.h.
userData() [2/2]
void bux::GLR::C_Parser::userData (void * p) inline
Definition at line 69 of file GLR.h.
Member Data Documentation
m_policy
const I_ParserPolicy& bux::GLR::C_Parser::m_policy
Definition at line 63 of file GLR.h.
Referenced by add(), and onError().
The documentation for this class was generated from the following files:
GLR.h
GLR.cpp