bux API Reference: bux::C_LockTillEnd Class Reference
bux::C_LockTillEnd Class Reference
#include <Sync.h>
Public Member Functions
C_LockTillEnd (const C_LockTillEnd &)=delete
C_LockTillEnd & operator= (const C_LockTillEnd &)=delete
C_LockTillEnd (I_Lockable &obj)
~C_LockTillEnd ()
operator bool () const
bool locked () const
void unlock ()
Public Attributes
I_Lockable & m_Obj
Detailed Description
Definition at line 75 of file Sync.h.
Constructor & Destructor Documentation
C_LockTillEnd() [1/2]
bux::C_LockTillEnd::C_LockTillEnd (const C_LockTillEnd &) delete
C_LockTillEnd() [2/2]
bux::C_LockTillEnd::C_LockTillEnd (I_Lockable & obj)
Definition at line 57 of file Sync.cpp.
~C_LockTillEnd()
bux::C_LockTillEnd::~C_LockTillEnd ()
Definition at line 63 of file Sync.cpp.
References unlock().
Member Function Documentation
locked()
bool bux::C_LockTillEnd::locked () const inline
Definition at line 91 of file Sync.h.
operator bool()
bux::C_LockTillEnd::operator bool () const inline
Definition at line 89 of file Sync.h.
operator=()
C_LockTillEnd& bux::C_LockTillEnd::operator= (const C_LockTillEnd &) delete
unlock()
void bux::C_LockTillEnd::unlock ()
Definition at line 68 of file Sync.cpp.
References m_Obj, and bux::I_Lockable::unlock().
Referenced by ~C_LockTillEnd().
Member Data Documentation
m_Obj
I_Lockable& bux::C_LockTillEnd::m_Obj
Definition at line 80 of file Sync.h.
Referenced by unlock().
The documentation for this class was generated from the following files:
Sync.h
Sync.cpp