bux API Reference: bux::C_MBCStr Class Reference
bux::C_MBCStr Class Reference
#include <UnicodeCvt.h>
Public Types
typedef void(* F_PushCh) (std::string &dst, char c)
Public Member Functions
C_MBCStr (T_Encoding codepage=0) noexcept
C_MBCStr (const C_MBCStr &)=delete
C_MBCStr & operator= (const C_MBCStr &)=delete
C_MBCStr (C_MBCStr &&other) noexcept
void operator= (C_MBCStr &&other) noexcept
C_MBCStr (std::string_view s, T_Encoding codepage=0) noexcept
void operator+= (std::string_view s)
template<typename T >
C_MBCStr (const T *ps, size_t size=0, T_Encoding codepage=0)
template<typename T >
void operator+= (const T *ps)
template<typename T >
C_MBCStr (const std::basic_string< T > &s, T_Encoding codepage=0)
template<typename T >
void operator+= (const std::basic_string< T > &s)
void append (const char *src, size_t srcBytes)
template<typename T >
void append (const T *ps, size_t size)
bool empty () const noexcept
const std::string & escape (F_PushCh pushCh) const
const std::string & escJSON () const
const std::string & strU8 () const
Detailed Description
Definition at line 117 of file UnicodeCvt.h.
Member Typedef Documentation
F_PushCh
typedef void(* bux::C_MBCStr::F_PushCh) (std::string &dst, char c)
Definition at line 122 of file UnicodeCvt.h.
Constructor & Destructor Documentation
C_MBCStr() [1/6]
bux::C_MBCStr::C_MBCStr (T_Encoding codepage = 0) inline noexcept
Definition at line 125 of file UnicodeCvt.h.
C_MBCStr() [2/6]
bux::C_MBCStr::C_MBCStr (const C_MBCStr &) delete
C_MBCStr() [3/6]
bux::C_MBCStr::C_MBCStr (C_MBCStr && other) noexcept
Definition at line 625 of file UnicodeCvt.cpp.
C_MBCStr() [4/6]
bux::C_MBCStr::C_MBCStr (std::string_view s, T_Encoding codepage = 0) inline noexcept
Definition at line 132 of file UnicodeCvt.h.
C_MBCStr() [5/6]
template<typename T > bux::C_MBCStr::C_MBCStr (const T * ps, size_t size = 0, T_Encoding codepage = 0) inline
Definition at line 135 of file UnicodeCvt.h.
References bux::append().
C_MBCStr() [6/6]
template<typename T > bux::C_MBCStr::C_MBCStr (const std::basic_string< T > & s, T_Encoding codepage = 0) inline
Definition at line 140 of file UnicodeCvt.h.
References bux::append().
Member Function Documentation
append() [1/2]
void bux::C_MBCStr::append (const char * src, size_t srcBytes)
Definition at line 654 of file UnicodeCvt.cpp.
References empty().
append() [2/2]
template<typename T > void bux::C_MBCStr::append (const T * ps, size_t size) inline
Definition at line 147 of file UnicodeCvt.h.
References bux::append().
empty()
bool bux::C_MBCStr::empty () const noexcept
Definition at line 697 of file UnicodeCvt.cpp.
Referenced by append(), and operator+=().
escape()
const std::string & bux::C_MBCStr::escape (F_PushCh pushCh) const
Definition at line 702 of file UnicodeCvt.cpp.
References bux::C_UnicodeIn::get().
Referenced by escJSON(), and strU8().
escJSON()
const std::string & bux::C_MBCStr::escJSON () const
Definition at line 721 of file UnicodeCvt.cpp.
References escape().
operator+=() [1/3]
template<typename T > void bux::C_MBCStr::operator+= (const std::basic_string< T > & s) inline
Definition at line 142 of file UnicodeCvt.h.
References bux::append().
operator+=() [2/3]
template<typename T > void bux::C_MBCStr::operator+= (const T * ps) inline
Definition at line 137 of file UnicodeCvt.h.
References bux::append().
operator+=() [3/3]
void bux::C_MBCStr::operator+= (std::string_view s)
Definition at line 641 of file UnicodeCvt.cpp.
References empty().
operator=() [1/2]
void bux::C_MBCStr::operator= (C_MBCStr && other) noexcept
Definition at line 633 of file UnicodeCvt.cpp.
operator=() [2/2]
C_MBCStr & bux::C_MBCStr::operator= (const C_MBCStr &) delete
strU8()
const std::string & bux::C_MBCStr::strU8 () const
Definition at line 746 of file UnicodeCvt.cpp.
References escape().
Referenced by bux::to_utf8().
The documentation for this class was generated from the following files:
UnicodeCvt.h
UnicodeCvt.cpp