bux API Reference: bux::C_ResourceStack< T > Class Template Reference
bux::C_ResourceStack< T > Class Template Reference
If ctor of type T properly handles ownership transfer, so does C_ResourceStack<T>
#include <Xtack.h>
Public Member Functions
C_ResourceStack (size_t minAlloc=4) noexcept
C_ResourceStack (C_ResourceStack &other)
template<class T_Iter >
C_ResourceStack (T_Iter beg, T_Iter end)
auto & operator= (C_ResourceStack &other)
auto & push ()
template<class T_Elem >
auto & push (T_Elem &t)
template<class T_Iter >
void push (T_Iter beg, T_Iter end)
Public Member Functions inherited from bux::C_StackBase< T >
C_StackBase (size_t minAlloc=4) noexcept
~C_StackBase ()
C_StackBase (const C_StackBase &)=delete
auto & operator[] (size_type i) noexcept
auto & operator[] (size_type i) const noexcept
auto & operator= (const C_StackBase &other)
template<class T_Iter >
void assign (T_Iter beg, T_Iter end)
auto begin () const noexcept
auto begin () noexcept
auto capacity () const
void clear ()
bool empty () const noexcept
auto end () const noexcept
auto end () noexcept
void pop (size_t n=1)
auto & push ()
template<class T_Iter >
void push (T_Iter beg, T_Iter end)
auto size () const noexcept
auto & top ()
auto & top () const
Additional Inherited Members
Public Types inherited from bux::C_StackBase< T >
typedef size_t size_type
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
Protected Member Functions inherited from bux::C_StackBase< T >
auto copyMinAlloc () const noexcept
T * pushRaw ()
Detailed Description
template<class T>
class bux::C_ResourceStack< T >
If ctor of type T properly handles ownership transfer, so does C_ResourceStack<T>
Definition at line 140 of file Xtack.h.
Constructor & Destructor Documentation
C_ResourceStack() [1/3]
template<class T > bux::C_ResourceStack< T >::C_ResourceStack (size_t minAlloc = 4) inline explicit noexcept
Definition at line 147 of file Xtack.h.
C_ResourceStack() [2/3]
template<class T > bux::C_ResourceStack< T >::C_ResourceStack (C_ResourceStack< T > & other) inline explicit
Definition at line 149 of file Xtack.h.
References bux::C_StackBase< T >::begin(), bux::C_StackBase< T >::end(), and bux::C_ResourceStack< T >::push().
C_ResourceStack() [3/3]
template<class T > template<class T_Iter > bux::C_ResourceStack< T >::C_ResourceStack (T_Iter beg, T_Iter end) inline
Definition at line 152 of file Xtack.h.
References bux::C_StackBase< T >::end(), and bux::C_ResourceStack< T >::push().
Member Function Documentation
operator=()
template<class T > auto & bux::C_ResourceStack< T >::operator= (C_ResourceStack< T > & other) inline
Definition at line 157 of file Xtack.h.
References bux::C_StackBase< T >::assign(), bux::C_StackBase< T >::begin(), and bux::C_StackBase< T >::end().
push() [1/3]
template<class T > auto & bux::C_ResourceStack< T >::push () inline
Definition at line 159 of file Xtack.h.
References bux::C_ResourceStack< T >::push().
Referenced by bux::C_ResourceStack< T >::C_ResourceStack(), bux::operator+=(), bux::operator<<(), and bux::C_ResourceStack< T >::push().
push() [2/3]
template<class T > template<class T_Elem > auto & bux::C_ResourceStack< T >::push (T_Elem & t) inline
Definition at line 162 of file Xtack.h.
References bux::C_StackBase< T >::pushRaw().
push() [3/3]
template<class T > template<class T_Iter > void bux::C_ResourceStack< T >::push (T_Iter beg, T_Iter end) inline
Definition at line 168 of file Xtack.h.
References bux::C_StackBase< T >::end(), and bux::C_StackBase< T >::push().
The documentation for this class was generated from the following file:
Xtack.h