bux API Reference: bux::C_Stack< T > Class Template Reference
bux::C_Stack< T > Class Template Reference
A much more succinct substitute of std::stack<std::vector<T> >
#include <Xtack.h>
Public Member Functions
C_Stack (size_t minAlloc=4) noexcept
C_Stack (const C_Stack &other)
template<class T_Iter >
C_Stack (T_Iter beg, T_Iter end)
C_Stack & operator= (const C_Stack &other)
auto & push ()
template<class T_Elem >
auto & push (const T_Elem &t)
template<class T_Iter >
void push (T_Iter beg, T_Iter end)
Public Member Functions inherited from bux::C_StackBase< T >
C_StackBase (size_t minAlloc=4) noexcept
~C_StackBase ()
C_StackBase (const C_StackBase &)=delete
auto & operator[] (size_type i) noexcept
auto & operator[] (size_type i) const noexcept
auto & operator= (const C_StackBase &other)
template<class T_Iter >
void assign (T_Iter beg, T_Iter end)
auto begin () const noexcept
auto begin () noexcept
auto capacity () const
void clear ()
bool empty () const noexcept
auto end () const noexcept
auto end () noexcept
void pop (size_t n=1)
auto & push ()
template<class T_Iter >
void push (T_Iter beg, T_Iter end)
auto size () const noexcept
auto & top ()
auto & top () const
Additional Inherited Members
Public Types inherited from bux::C_StackBase< T >
typedef size_t size_type
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
Protected Member Functions inherited from bux::C_StackBase< T >
auto copyMinAlloc () const noexcept
T * pushRaw ()
Detailed Description
template<class T>
class bux::C_Stack< T >
A much more succinct substitute of std::stack<std::vector<T> >
Definition at line 95 of file Xtack.h.
Constructor & Destructor Documentation
C_Stack() [1/3]
template<class T > bux::C_Stack< T >::C_Stack (size_t minAlloc = 4) inline explicit noexcept
Definition at line 102 of file Xtack.h.
C_Stack() [2/3]
template<class T > bux::C_Stack< T >::C_Stack (const C_Stack< T > & other) inline
Definition at line 104 of file Xtack.h.
References bux::C_StackBase< T >::begin(), bux::C_StackBase< T >::end(), and bux::C_Stack< T >::push().
C_Stack() [3/3]
template<class T > template<class T_Iter > bux::C_Stack< T >::C_Stack (T_Iter beg, T_Iter end) inline
Definition at line 107 of file Xtack.h.
References bux::C_StackBase< T >::end(), and bux::C_Stack< T >::push().
Member Function Documentation
operator=()
template<class T > C_Stack & bux::C_Stack< T >::operator= (const C_Stack< T > & other) inline
Definition at line 112 of file Xtack.h.
References bux::C_StackBase< T >::assign(), bux::C_StackBase< T >::begin(), and bux::C_StackBase< T >::end().
push() [1/3]
template<class T > auto & bux::C_Stack< T >::push () inline
Definition at line 114 of file Xtack.h.
References bux::C_StackBase< T >::push().
Referenced by bux::C_Stack< T >::C_Stack(), bux::operator+=(), and bux::operator<<().
push() [2/3]
template<class T > template<class T_Elem > auto & bux::C_Stack< T >::push (const T_Elem & t) inline
Definition at line 117 of file Xtack.h.
References bux::C_StackBase< T >::pushRaw().
push() [3/3]
template<class T > template<class T_Iter > void bux::C_Stack< T >::push (T_Iter beg, T_Iter end) inline
Definition at line 123 of file Xtack.h.
References bux::C_StackBase< T >::end(), and bux::C_StackBase< T >::push().
The documentation for this class was generated from the following file:
Xtack.h