bux API Reference: bux::C_SpinLock Class Reference
bux::C_SpinLock Class Reference
#include <AtomiX.h>
Public Member Functions
C_SpinLock (std::atomic_flag &lock_)
~C_SpinLock ()
void operator= (const C_SpinLock &)=delete
void unlock ()
Detailed Description
Definition at line 13 of file AtomiX.h.
Constructor & Destructor Documentation
C_SpinLock()
bux::C_SpinLock::C_SpinLock (std::atomic_flag & lock_)
Definition at line 8 of file AtomiX.cpp.
Referenced by operator=().
~C_SpinLock()
bux::C_SpinLock::~C_SpinLock () inline
Definition at line 19 of file AtomiX.h.
References unlock().
Member Function Documentation
operator=()
void bux::C_SpinLock::operator= (const C_SpinLock &) delete
References C_SpinLock().
unlock()
void bux::C_SpinLock::unlock ()
Definition at line 20 of file AtomiX.cpp.
Referenced by bux::C_SpinCacheT< T_Key, T_Value, YIELD_BEFORE_RETRY >::operator()(), and ~C_SpinLock().
The documentation for this class was generated from the following files:
AtomiX.h
AtomiX.cpp