bux API Reference: bux::C_RefObject Class Reference
bux::C_RefObject Class Reference abstract
#include <Sync.h>
Public Member Functions
C_RefObject (const C_RefObject &)=delete
C_RefObject & operator= (const C_RefObject &)=delete
C_RefObject (size_t initRefCount=0)
void decRef ()
bool incRef ()
void setZeroRefHandler (void(*pOnZeroRef)(void *), void *pData)
virtual void destroyASAP ()=0
Protected Member Functions
~C_RefObject ()
To ban pointer deletion.
void disableIncRef ()
auto refCount () const
Current refcount.
virtual void onNonzeroRef ()=0
virtual void onZeroRef ()=0
Protected Member Functions inherited from bux::I_Lockable
virtual ~I_Lockable ()=default
virtual bool lock ()=0
virtual void unlock ()=0
Detailed Description
Definition at line 102 of file Sync.h.
Constructor & Destructor Documentation
C_RefObject() [1/2]
bux::C_RefObject::C_RefObject (const C_RefObject &) delete
C_RefObject() [2/2]
bux::C_RefObject::C_RefObject (size_t initRefCount = 0)
Definition at line 9 of file Sync.cpp.
~C_RefObject()
bux::C_RefObject::~C_RefObject () inline protected
To ban pointer deletion.
Definition at line 122 of file Sync.h.
Member Function Documentation
decRef()
void bux::C_RefObject::decRef ()
Definition at line 16 of file Sync.cpp.
References onZeroRef().
destroyASAP()
virtual void bux::C_RefObject::destroyASAP () pure virtual
disableIncRef()
void bux::C_RefObject::disableIncRef () inline protected
Definition at line 124 of file Sync.h.
incRef()
bool bux::C_RefObject::incRef ()
Definition at line 33 of file Sync.cpp.
References onNonzeroRef().
Referenced by bux::C_RefTillEnd< T >::C_RefTillEnd().
onNonzeroRef()
virtual void bux::C_RefObject::onNonzeroRef () protected pure virtual
Referenced by incRef().
onZeroRef()
virtual void bux::C_RefObject::onZeroRef () protected pure virtual
Referenced by decRef().
operator=()
C_RefObject& bux::C_RefObject::operator= (const C_RefObject &) delete
refCount()
auto bux::C_RefObject::refCount () const inline protected
Current refcount.
Definition at line 126 of file Sync.h.
setZeroRefHandler()
void bux::C_RefObject::setZeroRefHandler (void(*)(void *) pOnZeroRef, void * pData)
Definition at line 45 of file Sync.cpp.
The documentation for this class was generated from the following files:
Sync.h
Sync.cpp