bux API Reference: bux::C_UnicodeIn Class Reference
bux::C_UnicodeIn Class Reference
#include <UnicodeCvt.h>
Public Member Functions
C_UnicodeIn (FH_ReadChar &&readc, T_Encoding codepage=0)
C_UnicodeIn (std::string_view sv, T_Encoding codepage=0)
C_UnicodeIn (std::string &&s, T_Encoding codepage=0)=delete
C_UnicodeIn (const char *s, T_Encoding codepage=0)
C_UnicodeIn (std::istream &in, T_Encoding codepage=0)
~C_UnicodeIn () noexcept
int get (T_Utf32 &c)
int get (T_Utf16 *dst)
int get (T_Utf8 *dst)
int lastError () const noexcept
T_Encoding encoding () const noexcept
Detailed Description
Definition at line 55 of file UnicodeCvt.h.
Constructor & Destructor Documentation
C_UnicodeIn() [1/5]
bux::C_UnicodeIn::C_UnicodeIn (FH_ReadChar && readc, T_Encoding codepage = 0)
Definition at line 163 of file UnicodeCvt.cpp.
Referenced by C_UnicodeIn(), C_UnicodeIn(), bux::to_utf8(), bux::to_utf8(), and bux::to_utf8().
C_UnicodeIn() [2/5]
bux::C_UnicodeIn::C_UnicodeIn (std::string_view sv, T_Encoding codepage = 0)
Definition at line 170 of file UnicodeCvt.cpp.
References C_UnicodeIn().
C_UnicodeIn() [3/5]
bux::C_UnicodeIn::C_UnicodeIn (std::string && s, T_Encoding codepage = 0) delete
C_UnicodeIn() [4/5]
bux::C_UnicodeIn::C_UnicodeIn (const char * s, T_Encoding codepage = 0) inline
Definition at line 63 of file UnicodeCvt.h.
References C_UnicodeIn().
C_UnicodeIn() [5/5]
bux::C_UnicodeIn::C_UnicodeIn (std::istream & in, T_Encoding codepage = 0)
Parameters
in Reference of input stream
codepage Encoding type of input stream. Value 0 to guess the finest.
HEADSUP: When codepage is 0 and in reference to a stream instance of type std::ifstream, the instance should be opened in binary mode with std::ios::binary for the case that the encoding is actually UTf-16(LE or BE) and input stream contains '\x1a' bytes (ascii EOF), e.g. as part of '\uff1a'. Or the input stream might hit EOF earlier than it should.
void foo(const std::string &path)
{
    std::ifstream fin{path, std::ios::binary};
    bux::C_UnicodeIn uin(fin);
    //... Rest of your code
}
Definition at line 175 of file UnicodeCvt.cpp.
~C_UnicodeIn()
bux::C_UnicodeIn::~C_UnicodeIn () noexcept
Definition at line 203 of file UnicodeCvt.cpp.
Member Function Documentation
encoding()
T_Encoding bux::C_UnicodeIn::encoding () const inline noexcept
Definition at line 72 of file UnicodeCvt.h.
get() [1/3]
int bux::C_UnicodeIn::get (T_Utf16 * dst)
Definition at line 230 of file UnicodeCvt.cpp.
References get().
get() [2/3]
int bux::C_UnicodeIn::get (T_Utf32 & c)
Definition at line 210 of file UnicodeCvt.cpp.
References lastError().
Referenced by get(), get(), and bux::C_LexTraits< C_LexUTF32 >::read().
get() [3/3]
int bux::C_UnicodeIn::get (T_Utf8 * dst)
Definition at line 251 of file UnicodeCvt.cpp.
References get().
lastError()
int bux::C_UnicodeIn::lastError () const inline noexcept
Definition at line 71 of file UnicodeCvt.h.
References lastError().
Referenced by get(), and lastError().
The documentation for this class was generated from the following files:
UnicodeCvt.h
UnicodeCvt.cpp