bux API Reference: bux::C_ParaLog Class Reference
bux::C_ParaLog Class Reference
#include <ParaLog.h>
Classes
class C_NodeArrayProxy
class C_NodeProxy
Public Member Functions
C_ParaLog (T_LocalZone tz_=T_LocalZone())
C_ParaLog (bool use_local_time)
template<class... T_Args>
bool addChild (T_Args &&...args)
template<class C_LogImpl, class C_Holder = typename C_AutoSinkHolderT<C_LogImpl>::type, class... T_Args>
bool addChildT (std::function< void(C_LogImpl &)> post_ctor={}, E_LogLevel ll=LL_VERBOSE, T_Args &&...args)
template<typename F>
C_NodeArrayProxy partitionBy (F f)
std::ostream * lockLog () override
Return non-null pointer if possible.
std::ostream * lockLog (E_LogLevel ll) override
Return non-null pointer if logging is permitted for the given log level ll.
void unlockLog (bool flush) override
If the previous call to lockLog() returned null, the behavior is undefined.
template<typename F>
auto partitionBy (F f) -> C_NodeArrayProxy
Friends
class C_NodeProxy
Additional Inherited Members
Public Attributes inherited from bux::I_SyncLog
const T_LocalZone tz
Protected Member Functions inherited from bux::I_SyncLog
I_SyncLog (T_LocalZone tz_)
~I_SyncLog ()=default
Pointer deletion is not expected.
Detailed Description
Thread-safe file log which can be configured to automatically change the output path according to the current timestamp. Apply bux::C_UseOstream to block any other thread WITHIN process from using it.
Definition at line 17 of file ParaLog.h.
Constructor & Destructor Documentation
C_ParaLog() [1/2]
bux::C_ParaLog::C_ParaLog (T_LocalZone tz_ = T_LocalZone()) inline explicit
Definition at line 30 of file ParaLog.h.
References bux::I_SyncLog::I_SyncLog().
Referenced by C_ParaLog().
C_ParaLog() [2/2]
bux::C_ParaLog::C_ParaLog (bool use_local_time) inline explicit
Definition at line 32 of file ParaLog.h.
References C_ParaLog(), and bux::local_zone().
Member Function Documentation
addChild()
template<class... T_Args> bool bux::C_ParaLog::addChild (T_Args &&... args)
Definition at line 184 of file ParaLog.h.
References bux::C_ParaLog::C_NodeProxy::addChild().
addChildT()
template<class C_LogImpl, class C_Holder, class... T_Args> bool bux::C_ParaLog::addChildT (std::function< void(C_LogImpl &)> post_ctor = {}, E_LogLevel ll = LL_VERBOSE, T_Args &&... args)
Definition at line 190 of file ParaLog.h.
References bux::C_ParaLog::C_NodeProxy::addChildT().
lockLog() [1/2]
std::ostream * bux::C_ParaLog::lockLog () override virtual
Return non-null pointer if possible.
Implements bux::I_SyncLog.
Definition at line 94 of file ParaLog.cpp.
References lockLog().
Referenced by lockLog(), and lockLog().
lockLog() [2/2]
std::ostream * bux::C_ParaLog::lockLog (E_LogLevel ll) override virtual
Return non-null pointer if logging is permitted for the given log level ll.
Implements bux::I_SyncLog.
Definition at line 99 of file ParaLog.cpp.
References lockLog().
partitionBy() [1/2]
template<typename F> C_NodeArrayProxy bux::C_ParaLog::partitionBy (F f) nodiscard
partitionBy() [2/2]
template<typename F> auto bux::C_ParaLog::partitionBy (F f) -> C_NodeArrayProxy
Definition at line 196 of file ParaLog.h.
References bux::C_ParaLog::C_NodeProxy::partitionBy().
unlockLog()
void bux::C_ParaLog::unlockLog (bool flush) override virtual
If the previous call to lockLog() returned null, the behavior is undefined.
Implements bux::I_SyncLog.
Definition at line 104 of file ParaLog.cpp.
Friends And Related Symbol Documentation
C_NodeProxy
friend class C_NodeProxy friend
Definition at line 65 of file ParaLog.h.
The documentation for this class was generated from the following files:
ParaLog.h
ParaLog.cpp