bux API Reference: bux::C_StackBase< T > Class Template Reference
bux::C_StackBase< T > Class Template Reference
Any given type is safely instantiated even though C_DtorFreeStack<T> does better for bytewise types.
#include <Xtack.h>
Public Types
typedef size_t size_type
typedef T value_type
typedef T * iterator
typedef const T * const_iterator
Public Member Functions
C_StackBase (size_t minAlloc=4) noexcept
~C_StackBase ()
C_StackBase (const C_StackBase &)=delete
auto & operator[] (size_type i) noexcept
auto & operator[] (size_type i) const noexcept
auto & operator= (const C_StackBase &other)
template<class T_Iter>
void assign (T_Iter beg, T_Iter end)
auto begin () const noexcept
auto begin () noexcept
auto capacity () const
void clear ()
bool empty () const noexcept
auto end () const noexcept
auto end () noexcept
void pop (size_t n=1)
auto & push ()
template<class T_Iter>
void push (T_Iter beg, T_Iter end)
auto size () const noexcept
auto & top ()
auto & top () const
Protected Member Functions
auto copyMinAlloc () const noexcept
T * pushRaw ()
Detailed Description
template<class T>
class bux::C_StackBase< T >
Any given type is safely instantiated even though C_DtorFreeStack<T> does better for bytewise types.
Definition at line 17 of file Xtack.h.
Member Typedef Documentation
const_iterator
template<class T> typedef const T* bux::C_StackBase< T >::const_iterator
Definition at line 25 of file Xtack.h.
iterator
template<class T> typedef T* bux::C_StackBase< T >::iterator
Definition at line 24 of file Xtack.h.
size_type
template<class T> typedef size_t bux::C_StackBase< T >::size_type
Definition at line 22 of file Xtack.h.
value_type
template<class T> typedef T bux::C_StackBase< T >::value_type
Definition at line 23 of file Xtack.h.
Constructor & Destructor Documentation
C_StackBase() [1/2]
template<class T> bux::C_StackBase< T >::C_StackBase (size_t minAlloc = 4) explicit noexcept
Definition at line 371 of file Xtack.h.
Referenced by C_StackBase(), and operator=().
~C_StackBase()
template<class T> bux::C_StackBase< T >::~C_StackBase ()
Definition at line 377 of file Xtack.h.
References clear().
C_StackBase() [2/2]
template<class T> bux::C_StackBase< T >::C_StackBase (const C_StackBase< T > &) delete
References C_StackBase().
Member Function Documentation
assign()
template<class T> template<class T_Iter> void bux::C_StackBase< T >::assign (T_Iter beg, T_Iter end) inline
Definition at line 40 of file Xtack.h.
References clear(), end(), and push().
Referenced by bux::C_ResourceStack< C_StateLR1 >::operator=(), bux::C_Stack< T >::operator=(), and operator=().
begin() [1/2]
template<class T> auto bux::C_StackBase< T >::begin () const inline noexcept
Definition at line 45 of file Xtack.h.
Referenced by bux::C_ResourceStack< C_StateLR1 >::C_ResourceStack(), bux::C_Stack< T >::C_Stack(), bux::operator+=(), bux::operator+=(), bux::operator<<(), bux::operator<<(), bux::operator<<(), bux::C_ResourceStack< C_StateLR1 >::operator=(), bux::C_Stack< T >::operator=(), and operator=().
begin() [2/2]
template<class T> auto bux::C_StackBase< T >::begin () inline noexcept
Definition at line 47 of file Xtack.h.
capacity()
template<class T> auto bux::C_StackBase< T >::capacity () const inline
Definition at line 49 of file Xtack.h.
clear()
template<class T> void bux::C_StackBase< T >::clear ()
Definition at line 384 of file Xtack.h.
References empty(), and pop().
Referenced by assign(), pushRaw(), and ~C_StackBase().
copyMinAlloc()
template<class T> auto bux::C_StackBase< T >::copyMinAlloc () const inline protected noexcept
Definition at line 78 of file Xtack.h.
Referenced by bux::C_ResourceStack< C_StateLR1 >::C_ResourceStack(), and bux::C_Stack< T >::C_Stack().
empty()
template<class T> bool bux::C_StackBase< T >::empty () const inline noexcept
Definition at line 53 of file Xtack.h.
Referenced by clear(), and bux::operator<<().
end() [1/2]
template<class T> auto bux::C_StackBase< T >::end () const inline noexcept
Definition at line 55 of file Xtack.h.
Referenced by assign(), bux::C_ResourceStack< C_StateLR1 >::C_ResourceStack(), bux::C_ResourceStack< C_StateLR1 >::C_ResourceStack(), bux::C_Stack< T >::C_Stack(), bux::C_Stack< T >::C_Stack(), bux::operator+=(), bux::operator+=(), bux::operator<<(), bux::C_ResourceStack< C_StateLR1 >::operator=(), bux::C_Stack< T >::operator=(), operator=(), bux::C_ResourceStack< C_StateLR1 >::push(), bux::C_Stack< T >::push(), and push().
end() [2/2]
template<class T> auto bux::C_StackBase< T >::end () inline noexcept
Definition at line 57 of file Xtack.h.
operator=()
template<class T> auto & bux::C_StackBase< T >::operator= (const C_StackBase< T > & other) inline
Definition at line 37 of file Xtack.h.
References assign(), begin(), C_StackBase(), and end().
operator[]() [1/2]
template<class T> auto & bux::C_StackBase< T >::operator[] (size_type i) const inline noexcept
Definition at line 35 of file Xtack.h.
operator[]() [2/2]
template<class T> auto & bux::C_StackBase< T >::operator[] (size_type i) inline noexcept
Definition at line 33 of file Xtack.h.
pop()
template<class T> void bux::C_StackBase< T >::pop (size_t n = 1)
Definition at line 391 of file Xtack.h.
Referenced by clear().
push() [1/2]
template<class T> auto & bux::C_StackBase< T >::push () inline
Definition at line 61 of file Xtack.h.
References pushRaw().
Referenced by assign(), bux::C_ResourceStack< C_StateLR1 >::push(), bux::C_Stack< T >::push(), and bux::C_Stack< T >::push().
push() [2/2]
template<class T> template<class T_Iter> void bux::C_StackBase< T >::push (T_Iter beg, T_Iter end)
Definition at line 403 of file Xtack.h.
References end(), and pushRaw().
pushRaw()
template<class T> T * bux::C_StackBase< T >::pushRaw () protected
Definition at line 416 of file Xtack.h.
References clear().
Referenced by bux::C_ResourceStack< C_StateLR1 >::push(), bux::C_Stack< T >::push(), push(), and push().
size()
template<class T> auto bux::C_StackBase< T >::size () const inline noexcept
Definition at line 68 of file Xtack.h.
Referenced by bux::operator<<(), and bux::operator<<().
top() [1/2]
template<class T> auto & bux::C_StackBase< T >::top () inline
Definition at line 70 of file Xtack.h.
top() [2/2]
template<class T> auto & bux::C_StackBase< T >::top () const inline
Definition at line 72 of file Xtack.h.
The documentation for this class was generated from the following file:
Xtack.h