bux API Reference: bux::C_ParserLogCount Class Reference
bux::C_ParserLogCount Class Reference abstract
#include <ParserBase.h>
Public Member Functions
auto getCount (E_LogLevel ll) const
void log (E_LogLevel ll, const C_SourcePos &pos, std::string_view message)
Protected Member Functions
virtual std::string toStr (const C_SourcePos &pos) const
virtual void println (const std::string &line)=0
Protected Attributes
std::array< unsigned, 5 > m_count {}
Detailed Description
Definition at line 73 of file ParserBase.h.
Member Function Documentation
getCount()
auto bux::C_ParserLogCount::getCount (E_LogLevel ll) const inline
Definition at line 78 of file ParserBase.h.
References m_count.
log()
void bux::C_ParserLogCount::log (E_LogLevel ll, const C_SourcePos & pos, std::string_view message)
Definition at line 11 of file ParserBase.cpp.
References m_count, println(), and toStr().
println()
virtual void bux::C_ParserLogCount::println (const std::string & line) protected pure virtual
Referenced by log().
toStr()
std::string bux::C_ParserLogCount::toStr (const C_SourcePos & pos) const protected virtual
Definition at line 18 of file ParserBase.cpp.
References bux::C_SourcePos::m_Col, bux::C_SourcePos::m_Line, and bux::C_SourcePos::m_Source.
Referenced by log().
Member Data Documentation
m_count
std::array<unsigned,5> bux::C_ParserLogCount::m_count {} protected
Definition at line 84 of file ParserBase.h.
Referenced by getCount(), and log().
The documentation for this class was generated from the following files:
ParserBase.h
ParserBase.cpp