bux API Reference: bux::I_ReenterableLog Struct Reference
bux::I_ReenterableLog Struct Reference abstract
Thread-unsafe implementation is preferred for performance.
#include <SyncLog.h>
Public Member Functions
virtual ~I_ReenterableLog ()=default
Pointer deletion is hereby granted.
virtual std::ostream * useLog ()=0
Return non-null pointer if possible.
virtual std::ostream * useLog (E_LogLevel ll)=0
Return non-null pointer if logging is permitted to log level ll.
virtual void unuseLog (bool flush)=0
If the previous call to lockLog() returned null, the behavior is undefined.
Detailed Description
Thread-unsafe implementation is preferred for performance.
Definition at line 34 of file SyncLog.h.
Constructor & Destructor Documentation
~I_ReenterableLog()
virtual bux::I_ReenterableLog::~I_ReenterableLog () virtual default
Pointer deletion is hereby granted.
Member Function Documentation
unuseLog()
virtual void bux::I_ReenterableLog::unuseLog (bool flush) pure virtual
If the previous call to lockLog() returned null, the behavior is undefined.
Implemented in bux::C_ReenterableLogger< C_SinkRefHolder >, and bux::C_ReenterableLogger< typename C_AutoSinkHolderT< C_LogImpl >::type >.
Referenced by bux::C_SyncLogger::unlockLog().
useLog() [1/2]
virtual std::ostream * bux::I_ReenterableLog::useLog () pure virtual
Return non-null pointer if possible.
Implemented in bux::C_ReenterableLogger< C_SinkRefHolder >, and bux::C_ReenterableLogger< typename C_AutoSinkHolderT< C_LogImpl >::type >.
Referenced by bux::C_SyncLogger::lockLog(), and bux::C_SyncLogger::lockLog().
useLog() [2/2]
virtual std::ostream * bux::I_ReenterableLog::useLog (E_LogLevel ll) pure virtual
Return non-null pointer if logging is permitted to log level ll.
Implemented in bux::C_ReenterableLogger< C_SinkRefHolder >, and bux::C_ReenterableLogger< typename C_AutoSinkHolderT< C_LogImpl >::type >.
The documentation for this struct was generated from the following file:
SyncLog.h