bux API Reference: bux::C_LexTraits< C_LexUTF32 > Struct Reference
bux::C_LexTraits< C_LexUTF32 > Struct Reference
#include <ScannerBase.h>
Static Public Member Functions
static void appendUTF8 (std::string &u8, C_LexUTF32 src)
static unsigned columnsInDisplay (C_LexUTF32 ch) noexcept
static constexpr auto id (C_LexUTF32 ch) noexcept
static bool read (C_UnicodeIn &uin, C_LexUTF32 &ch)
static void setId (C_LexUTF32 &ch, T_LexID id) noexcept
Detailed Description
Definition at line 50 of file ScannerBase.h.
Member Function Documentation
appendUTF8()
static void bux::C_LexTraits< C_LexUTF32 >::appendUTF8 (std::string & u8, C_LexUTF32 src) inline static
Definition at line 52 of file ScannerBase.h.
References bux::C_LexUTF32::m_U32, and bux::to_utf8().
columnsInDisplay()
static unsigned bux::C_LexTraits< C_LexUTF32 >::columnsInDisplay (C_LexUTF32 ch) inline static noexcept
Definition at line 56 of file ScannerBase.h.
id()
static constexpr auto bux::C_LexTraits< C_LexUTF32 >::id (C_LexUTF32 ch) inline static constexpr noexcept
Definition at line 64 of file ScannerBase.h.
read()
static bool bux::C_LexTraits< C_LexUTF32 >::read (C_UnicodeIn & uin, C_LexUTF32 & ch) inline static
Definition at line 68 of file ScannerBase.h.
References bux::C_UnicodeIn::get(), and bux::C_LexUTF32::m_U32.
setId()
static void bux::C_LexTraits< C_LexUTF32 >::setId (C_LexUTF32 & ch, T_LexID id) inline static noexcept
Definition at line 72 of file ScannerBase.h.
References bux::C_LexTraits< T_LexCh >::id().
The documentation for this struct was generated from the following file:
ScannerBase.h