bux API Reference: bux::LR1::C_NewLex< T_Data > Struct Template Reference
bux::LR1::C_NewLex< T_Data > Struct Template Reference
#include <LR1.h>
Public Member Functions
C_NewLex ()=default
C_NewLex (C_LexInfo &i)
template<class... T_Args>
C_NewLex (T_Args &&...args)
Public Member Functions inherited from bux::C_NewNode< C_LexDataT< T_Data > >
C_NewNode ()
C_NewNode (T_Args &&...args)
Public Member Functions inherited from bux::C_AutoNode< C_LexDataT< T_Data > >
constexpr C_AutoNode () noexcept
constexpr C_AutoNode (C_LexDataT< T_Data > *p, bool owned) noexcept
C_AutoNode (C_AutoNode &another) noexcept
C_AutoNode (C_AutoNode< T2 > &another) noexcept
~C_AutoNode ()
void operator= (C_AutoNode &another)
void operator= (C_AutoNode< T2 > &another)
operator bool () const noexcept
operator T2 * () const noexcept
C_LexDataT< T_Data > * operator-> () const noexcept
C_LexDataT< T_Data > ** operator& () noexcept
C_LexDataT< T_Data > & operator* () const noexcept
void assign (C_LexDataT< T_Data > *ptr, bool owned)
void reset (C_LexDataT< T_Data > *ptr) noexcept
void clear () noexcept
C_LexDataT< T_Data > * disown () noexcept
C_LexDataT< T_Data > * get () const noexcept
bool owned () const noexcept
void swap (C_AutoNode &another) noexcept
bool takeOver (C_AutoNode< T2 > &another)
Additional Inherited Members
Protected Member Functions inherited from bux::C_NewNode< C_LexDataT< T_Data > >
constexpr C_NewNode (C_Void) noexcept
Detailed Description
template<class T_Data>
struct bux::LR1::C_NewLex< T_Data >
Definition at line 128 of file LR1.h.
Constructor & Destructor Documentation
C_NewLex() [1/3]
template<class T_Data> bux::LR1::C_NewLex< T_Data >::C_NewLex () default
C_NewLex() [2/3]
template<class T_Data> bux::LR1::C_NewLex< T_Data >::C_NewLex (C_LexInfo & i) inline explicit
Definition at line 132 of file LR1.h.
References bux::C_AutoNode< C_LexDataT< T_Data > >::assign(), bux::C_NewNode< C_LexDataT< T_Data > >::C_NewNode(), bux::C_LexInfoT< T, C_Ptr >::m_attr, RUNTIME_ERROR, and bux::C_AutoNode< C_LexDataT< T_Data > >::takeOver().
C_NewLex() [3/3]
template<class T_Data> template<class... T_Args> bux::LR1::C_NewLex< T_Data >::C_NewLex (T_Args &&... args) inline explicit
Definition at line 140 of file LR1.h.
References bux::C_NewNode< C_LexDataT< T_Data > >::C_NewNode().
The documentation for this struct was generated from the following file:
LR1.h