bux API Reference: bux::GLR::I_ParserPolicy Struct Reference
bux::GLR::I_ParserPolicy Struct Reference abstract
#include <GLR.h>
Classes
struct C_ReduceInfo
Public Member Functions
virtual std::vector< T_ActionId > action (T_StateID state, T_LexID token) const =0
virtual bool changeToken (T_LexID &token, C_LexPtr &attr) const
virtual size_t getAcceptId () const =0
virtual bool getTokenName (T_LexID token, std::string &name) const
virtual T_StateID nextState (T_StateID state, T_LexID lex) const =0
virtual void getReduceInfo (size_t prodId, C_ReduceInfo &info) const =0
virtual void onError (C_Parser &parser, const C_SourcePos &pos, std::string_view message) const =0
std::string printToken (T_LexID token) const
Detailed Description
Definition at line 35 of file GLR.h.
Member Function Documentation
action()
virtual std::vector<T_ActionId> bux::GLR::I_ParserPolicy::action (T_StateID state, T_LexID token) const pure virtual
Referenced by bux::GLR::C_Parser::add().
changeToken()
bool bux::GLR::I_ParserPolicy::changeToken (T_LexID & token, C_LexPtr & attr) const virtual
Definition at line 11 of file GLR.cpp.
Referenced by bux::GLR::C_Parser::add().
getAcceptId()
virtual size_t bux::GLR::I_ParserPolicy::getAcceptId () const pure virtual
Referenced by bux::GLR::C_Parser::add().
getReduceInfo()
virtual void bux::GLR::I_ParserPolicy::getReduceInfo (size_t prodId, C_ReduceInfo & info) const pure virtual
getTokenName()
bool bux::GLR::I_ParserPolicy::getTokenName (T_LexID token, std::string & name) const virtual
Definition at line 16 of file GLR.cpp.
Referenced by printToken().
nextState()
virtual T_StateID bux::GLR::I_ParserPolicy::nextState (T_StateID state, T_LexID lex) const pure virtual
Referenced by bux::GLR::C_Parser::add().
onError()
virtual void bux::GLR::I_ParserPolicy::onError (C_Parser & parser, const C_SourcePos & pos, std::string_view message) const pure virtual
Referenced by bux::GLR::C_Parser::onError().
printToken()
std::string bux::GLR::I_ParserPolicy::printToken (T_LexID token) const
Definition at line 21 of file GLR.cpp.
References bux::asciiLiteral(), getTokenName(), bux::ROOT_NID, bux::TID_EOF, and bux::TOKENGEN_LB.
Referenced by bux::GLR::C_Parser::add().
The documentation for this struct was generated from the following files:
GLR.h
GLR.cpp