bux API Reference: bux::I_Scanner< T_Char > Struct Template Reference
bux::I_Scanner< T_Char > Struct Template Reference abstract
#include <ScannerBase.h>
Public Member Functions
virtual ~I_Scanner ()=default
virtual void add (unsigned col, T_Char c)=0
virtual void setLine (unsigned line)=0
virtual void setSource (std::string_view src)=0
Detailed Description
template<class T_Char>
struct bux::I_Scanner< T_Char >
Definition at line 17 of file ScannerBase.h.
Constructor & Destructor Documentation
~I_Scanner()
template<class T_Char > virtual bux::I_Scanner< T_Char >::~I_Scanner () virtual default
Member Function Documentation
add()
template<class T_Char > virtual void bux::I_Scanner< T_Char >::add (unsigned col, T_Char c) pure virtual
Implemented in bux::C_ScannerImpl< T_Input, T_State, T_Char, C_Traits >.
Referenced by bux::scanFile().
setLine()
template<class T_Char > virtual void bux::I_Scanner< T_Char >::setLine (unsigned line) pure virtual
Implemented in bux::C_ScannerImpl< T_Input, T_State, T_Char, C_Traits >.
Referenced by bux::scanFile().
setSource()
template<class T_Char > virtual void bux::I_Scanner< T_Char >::setSource (std::string_view src) pure virtual
Implemented in bux::C_ScannerImpl< T_Input, T_State, T_Char, C_Traits >.
Referenced by bux::scanFile().
The documentation for this struct was generated from the following file:
ScannerBase.h